package spiders1;

/**
 *
 * @author .
 */
public class EasyUI extends javax.swing.JFrame {

        /**
         * Creates new form EasyUI
         */
        public EasyUI() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                MainPanel = new javax.swing.JPanel();
                S2Card5 = new javax.swing.JButton();
                S2Card4 = new javax.swing.JButton();
                S2Card3 = new javax.swing.JButton();
                S2Card2 = new javax.swing.JButton();
                S2Card1 = new javax.swing.JButton();
                S1Card5 = new javax.swing.JButton();
                S1Card4 = new javax.swing.JButton();
                S1Card3 = new javax.swing.JButton();
                S1Card2 = new javax.swing.JButton();
                S3Card5 = new javax.swing.JButton();
                S1Card1 = new javax.swing.JButton();
                S3Card4 = new javax.swing.JButton();
                S3Card3 = new javax.swing.JButton();
                S3Card2 = new javax.swing.JButton();
                S4Card5 = new javax.swing.JButton();
                S4Card4 = new javax.swing.JButton();
                S3Card1 = new javax.swing.JButton();
                S4Card3 = new javax.swing.JButton();
                S4Card2 = new javax.swing.JButton();
                S5Card4 = new javax.swing.JButton();
                S4Card1 = new javax.swing.JButton();
                S5Card3 = new javax.swing.JButton();
                S5Card2 = new javax.swing.JButton();
                S6Card4 = new javax.swing.JButton();
                S5Card1 = new javax.swing.JButton();
                S6Card3 = new javax.swing.JButton();
                S6Card2 = new javax.swing.JButton();
                S6Card1 = new javax.swing.JButton();
                S7Card4 = new javax.swing.JButton();
                S7Card3 = new javax.swing.JButton();
                S7Card2 = new javax.swing.JButton();
                S7Card1 = new javax.swing.JButton();
                BtnRestart = new javax.swing.JButton();
                BtnPlace = new javax.swing.JButton();
                S8Card4 = new javax.swing.JButton();
                S8Card3 = new javax.swing.JButton();
                S8Card2 = new javax.swing.JButton();
                S8Card1 = new javax.swing.JButton();
                S9Card4 = new javax.swing.JButton();
                S9Card3 = new javax.swing.JButton();
                S9Card2 = new javax.swing.JButton();
                S10Card4 = new javax.swing.JButton();
                S9Card1 = new javax.swing.JButton();
                S10Card3 = new javax.swing.JButton();
                S10Card2 = new javax.swing.JButton();
                S10Card1 = new javax.swing.JButton();
                S0Card1 = new javax.swing.JButton();
                S0Card2 = new javax.swing.JButton();
                S0Card3 = new javax.swing.JButton();
                S0Card4 = new javax.swing.JButton();
                S0Card5 = new javax.swing.JButton();
                BtnDeal = new javax.swing.JButton();
                LblRest = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                MainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                S2Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S2Card5.setOpaque(false);
                MainPanel.add(S2Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, 100));

                S2Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S2Card4.setOpaque(false);
                MainPanel.add(S2Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 100));

                S2Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S2Card3.setOpaque(false);
                MainPanel.add(S2Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, 100));

                S2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S2Card2.setOpaque(false);
                MainPanel.add(S2Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, 100));

                S2Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S2Card1.setOpaque(false);
                MainPanel.add(S2Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 70, 100));

                S1Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S1Card5.setOpaque(false);
                MainPanel.add(S1Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 100));

                S1Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S1Card4.setOpaque(false);
                MainPanel.add(S1Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 100));

                S1Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S1Card3.setOpaque(false);
                MainPanel.add(S1Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 100));

                S1Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S1Card2.setOpaque(false);
                MainPanel.add(S1Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 100));

                S3Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S3Card5.setOpaque(false);
                MainPanel.add(S3Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 70, 100));

                S1Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/back2.jpg"))); // NOI18N
                S1Card1.setOpaque(false);
                MainPanel.add(S1Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 100));

                S3Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S3Card4.setOpaque(false);
                MainPanel.add(S3Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 100));

                S3Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S3Card3.setOpaque(false);
                MainPanel.add(S3Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 70, 100));

                S3Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S3Card2.setOpaque(false);
                MainPanel.add(S3Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 70, 100));

                S4Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S4Card5.setOpaque(false);
                MainPanel.add(S4Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 70, 100));

                S4Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S4Card4.setOpaque(false);
                MainPanel.add(S4Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, 100));

                S3Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S3Card1.setOpaque(false);
                MainPanel.add(S3Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 100));

                S4Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S4Card3.setOpaque(false);
                MainPanel.add(S4Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 70, 100));

                S4Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S4Card2.setOpaque(false);
                MainPanel.add(S4Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 70, 100));

                S5Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S5Card4.setOpaque(false);
                MainPanel.add(S5Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 70, 100));

                S4Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S4Card1.setOpaque(false);
                MainPanel.add(S4Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 70, 100));

                S5Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S5Card3.setOpaque(false);
                MainPanel.add(S5Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 70, 100));

                S5Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S5Card2.setOpaque(false);
                MainPanel.add(S5Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 70, 100));

                S6Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S6Card4.setOpaque(false);
                MainPanel.add(S6Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 70, 100));

                S5Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S5Card1.setOpaque(false);
                MainPanel.add(S5Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 70, 100));

                S6Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S6Card3.setOpaque(false);
                MainPanel.add(S6Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 70, 100));

                S6Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S6Card2.setOpaque(false);
                MainPanel.add(S6Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 70, 100));

                S6Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S6Card1.setOpaque(false);
                MainPanel.add(S6Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 70, 100));

                S7Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S7Card4.setOpaque(false);
                MainPanel.add(S7Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 70, 100));

                S7Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S7Card3.setOpaque(false);
                MainPanel.add(S7Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 70, 100));

                S7Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S7Card2.setOpaque(false);
                MainPanel.add(S7Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 70, 100));

                S7Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S7Card1.setOpaque(false);
                MainPanel.add(S7Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 70, 100));

                BtnRestart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                BtnRestart.setText("Restart");
                MainPanel.add(BtnRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 100, 60));

                BtnPlace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                BtnPlace.setText("Place");
                MainPanel.add(BtnPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 60));

                S8Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S8Card4.setOpaque(false);
                MainPanel.add(S8Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 70, 100));

                S8Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S8Card3.setOpaque(false);
                MainPanel.add(S8Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 70, 100));

                S8Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S8Card2.setOpaque(false);
                MainPanel.add(S8Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 70, 100));

                S8Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S8Card1.setOpaque(false);
                MainPanel.add(S8Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 70, 100));

                S9Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S9Card4.setOpaque(false);
                MainPanel.add(S9Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 70, 100));

                S9Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S9Card3.setOpaque(false);
                MainPanel.add(S9Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 70, 100));

                S9Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S9Card2.setOpaque(false);
                MainPanel.add(S9Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 70, 100));

                S10Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S10Card4.setOpaque(false);
                MainPanel.add(S10Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 70, 100));

                S9Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S9Card1.setOpaque(false);
                MainPanel.add(S9Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 70, 100));

                S10Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S10Card3.setOpaque(false);
                MainPanel.add(S10Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 70, 100));

                S10Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S10Card2.setOpaque(false);
                MainPanel.add(S10Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 70, 100));

                S10Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S10Card1.setOpaque(false);
                MainPanel.add(S10Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 70, 100));

                S0Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S0Card1.setOpaque(false);
                MainPanel.add(S0Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 70, 100));

                S0Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S0Card2.setOpaque(false);
                MainPanel.add(S0Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 70, 100));

                S0Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S0Card3.setOpaque(false);
                MainPanel.add(S0Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 70, 100));

                S0Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S0Card4.setOpaque(false);
                MainPanel.add(S0Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, 70, 100));

                S0Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/back2.jpg"))); // NOI18N
                S0Card5.setOpaque(false);
                MainPanel.add(S0Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 70, 100));

                BtnDeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                BtnDeal.setText("Deal Cards");
                MainPanel.add(BtnDeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 150, 60));

                LblRest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                LblRest.setText("Deck: 50 card(s) left");
                MainPanel.add(LblRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 170, 30));

                getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 610));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
	 * Returns the image that corresponds to the input card.
	 * Image names have the format "[Rank][Suit].GIF" or "[Rank][Suit]S.GIF",
	 * for example "aceclubs.GIF" or "8heartsS.GIF". The "S" indicates that
	 * the card is selected.
	 *
	 * @param c Card to get the image for
	 * @param isSelected flag that indicates if the card is selected
	 * @return String representation of the image
	 */
	private String imageFileName(Card c, boolean isSelected) {
		String str = "cards/";
		if (c == null) {
			return "cards/back1.GIF";
		}
		str += c.rank() + c.suit();
		if (isSelected) {
			str += "S";
		}
		str += ".GIF";
		return str;
	}

        
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
               
                Board board = new EasyBoard();
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new EasyUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BtnDeal;
        private javax.swing.JButton BtnPlace;
        private javax.swing.JButton BtnRestart;
        private javax.swing.JLabel LblRest;
        private javax.swing.JPanel MainPanel;
        private javax.swing.JButton S0Card1;
        private javax.swing.JButton S0Card2;
        private javax.swing.JButton S0Card3;
        private javax.swing.JButton S0Card4;
        private javax.swing.JButton S0Card5;
        private javax.swing.JButton S10Card1;
        private javax.swing.JButton S10Card2;
        private javax.swing.JButton S10Card3;
        private javax.swing.JButton S10Card4;
        private javax.swing.JButton S1Card1;
        private javax.swing.JButton S1Card2;
        private javax.swing.JButton S1Card3;
        private javax.swing.JButton S1Card4;
        private javax.swing.JButton S1Card5;
        private javax.swing.JButton S2Card1;
        private javax.swing.JButton S2Card2;
        private javax.swing.JButton S2Card3;
        private javax.swing.JButton S2Card4;
        private javax.swing.JButton S2Card5;
        private javax.swing.JButton S3Card1;
        private javax.swing.JButton S3Card2;
        private javax.swing.JButton S3Card3;
        private javax.swing.JButton S3Card4;
        private javax.swing.JButton S3Card5;
        private javax.swing.JButton S4Card1;
        private javax.swing.JButton S4Card2;
        private javax.swing.JButton S4Card3;
        private javax.swing.JButton S4Card4;
        private javax.swing.JButton S4Card5;
        private javax.swing.JButton S5Card1;
        private javax.swing.JButton S5Card2;
        private javax.swing.JButton S5Card3;
        private javax.swing.JButton S5Card4;
        private javax.swing.JButton S6Card1;
        private javax.swing.JButton S6Card2;
        private javax.swing.JButton S6Card3;
        private javax.swing.JButton S6Card4;
        private javax.swing.JButton S7Card1;
        private javax.swing.JButton S7Card2;
        private javax.swing.JButton S7Card3;
        private javax.swing.JButton S7Card4;
        private javax.swing.JButton S8Card1;
        private javax.swing.JButton S8Card2;
        private javax.swing.JButton S8Card3;
        private javax.swing.JButton S8Card4;
        private javax.swing.JButton S9Card1;
        private javax.swing.JButton S9Card2;
        private javax.swing.JButton S9Card3;
        private javax.swing.JButton S9Card4;
        // End of variables declaration//GEN-END:variables
}
