package spiders1;

/**
 *
 * @author .
 */
import javax.swing.ButtonGroup;
public class MainFrame extends javax.swing.JFrame {

        /**
         * Creates new form MainFrame
         */
        public MainFrame() {
                initComponents();
                GroupButtons();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                SelectionPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                CheckHard = new javax.swing.JRadioButton();
                CheckEasy = new javax.swing.JRadioButton();
                BtnPlay = new javax.swing.JButton();
                CheckMedium = new javax.swing.JRadioButton();
                BtnExit = new javax.swing.JButton();
                LblBackgroundimg = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("SOLITAIRE");
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                SelectionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
                SelectionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                SelectionPanel.setFocusable(false);
                SelectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+1f));
                jLabel1.setText("Spider Solitaire");
                SelectionPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

                CheckHard.setText("Hard");
                CheckHard.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CheckHardActionPerformed(evt);
                        }
                });
                SelectionPanel.add(CheckHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

                CheckEasy.setText("Easy");
                CheckEasy.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CheckEasyActionPerformed(evt);
                        }
                });
                SelectionPanel.add(CheckEasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

                BtnPlay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                BtnPlay.setText("PLAY");
                BtnPlay.setToolTipText("Play the game!!!");
                BtnPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                BtnPlay.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnPlayActionPerformed(evt);
                        }
                });
                SelectionPanel.add(BtnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 110, 50));

                CheckMedium.setText("Medium");
                CheckMedium.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CheckMediumActionPerformed(evt);
                        }
                });
                SelectionPanel.add(CheckMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

                getContentPane().add(SelectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 600, 230));

                BtnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                BtnExit.setText("EXIT");
                BtnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                BtnExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnExitActionPerformed(evt);
                        }
                });
                getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 90, 30));

                LblBackgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevens2/cards/green_felt.jpg"))); // NOI18N
                getContentPane().add(LblBackgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        ButtonGroup choice;
        void GroupButtons(){
                choice = new ButtonGroup();
                choice.add(CheckEasy);
                choice.add(CheckMedium);
                choice.add(CheckHard);
        }
        
        
        private void BtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlayActionPerformed
                // TODO add your handling code here:
                if (CheckEasy.isSelected()){
                        this.setVisible(false);
                        new EasyUI().setVisible(true);
                }
                else if (CheckMedium.isSelected()){
                        this.setVisible(false);
                        new MediumUI().setVisible(true);
                }
                else if (CheckHard.isSelected()){
                        this.setVisible(false);
                        new HardUI().setVisible(true);
                }
        }//GEN-LAST:event_BtnPlayActionPerformed

        private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
                System.exit(0);
        }//GEN-LAST:event_BtnExitActionPerformed

        private void CheckEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEasyActionPerformed
                if (CheckEasy.isSelected()){
                        CheckMedium.setSelected(false);
                        CheckHard.setSelected(false);
                }
        }//GEN-LAST:event_CheckEasyActionPerformed

        private void CheckMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMediumActionPerformed
                if (CheckMedium.isSelected()){
                        CheckEasy.setSelected(false);
                        CheckHard.setSelected(false);
                }
        }//GEN-LAST:event_CheckMediumActionPerformed

        private void CheckHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckHardActionPerformed
                // TODO add your handling code here:
                if (CheckHard.isSelected()){
                        CheckMedium.setSelected(false);
                        CheckEasy.setSelected(false);
                }
        }//GEN-LAST:event_CheckHardActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BtnExit;
        private javax.swing.JButton BtnPlay;
        private javax.swing.JRadioButton CheckEasy;
        private javax.swing.JRadioButton CheckHard;
        private javax.swing.JRadioButton CheckMedium;
        private javax.swing.JLabel LblBackgroundimg;
        private javax.swing.JPanel SelectionPanel;
        private javax.swing.JLabel jLabel1;
        // End of variables declaration//GEN-END:variables
}
